# Generated by Django 5.2.1 on 2025-05-16 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='date_naissance',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='email',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='telephone',
        ),
        migrations.AddField(
            model_name='candidat',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
