# Generated by Django 5.2 on 2025-10-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0002_remove_candidat_date_naissance_remove_candidat_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='nom',
            field=models.CharField(default='', max_length=100, verbose_name='Nom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='prenom',
            field=models.CharField(default='', max_length=100, verbose_name='Prénom'),
            preserve_default=False,
        ),
    ]
