# Generated by Django 5.2 on 2025-10-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0003_alter_utilisateur_options_utilisateur_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offreemploi',
            name='competences',
            field=models.TextField(default='', help_text='Séparez les compétences par des virgules', verbose_name='Compétences requises'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='entreprise',
            field=models.CharField(default='', max_length=255, verbose_name='Entreprise'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='localisation',
            field=models.CharField(default='', max_length=255, verbose_name='Localisation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo entreprise'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='nb_candidats',
            field=models.IntegerField(default=0, verbose_name='Nombre de candidats'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='nouveau',
            field=models.BooleanField(default=True, verbose_name='Nouvelle offre'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='salaire_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Salaire maximum (FCFA)'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='salaire_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Salaire minimum (FCFA)'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='temps_plein',
            field=models.BooleanField(default=True, verbose_name='Temps plein'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='type_contrat',
            field=models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('Stage', 'Stage'), ('Alternance', 'Alternance'), ('Freelance', 'Freelance')], default='CDI', max_length=50, verbose_name='Type de contrat'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='urgent',
            field=models.BooleanField(default=False, verbose_name='Offre urgente'),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='date_limite',
            field=models.DateField(verbose_name='Date limite de candidature'),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='titre',
            field=models.CharField(max_length=255, verbose_name='Titre du poste'),
        ),
    ]
