# Generated by Django 5.2 on 2025-10-16 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0004_offreemploi_competences_offreemploi_entreprise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('recruteur', 'Recruteur'), ('candidat', 'Candidat'), ('admin', 'Administrateur')], default='candidat', max_length=20),
        ),
        migrations.CreateModel(
            name='RH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.CharField(blank=True, max_length=200, verbose_name='Entreprise')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('poste', models.CharField(blank=True, max_length=100, verbose_name='Poste')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_rh', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recruteur (RH)',
                'verbose_name_plural': 'Recruteurs (RH)',
            },
        ),
    ]
