# Generated by Django 5.2 on 2025-10-16 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0005_alter_utilisateur_role_rh'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rh',
            options={},
        ),
        migrations.RemoveField(
            model_name='rh',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='rh',
            name='poste',
        ),
        migrations.RemoveField(
            model_name='rh',
            name='telephone',
        ),
        migrations.AlterField(
            model_name='rh',
            name='entreprise',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rh',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
