# Generated by Django 5.2 on 2025-10-17 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0006_alter_rh_options_remove_rh_date_creation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_rapport', models.CharField(choices=[('offres', "Offres d'Emploi"), ('candidatures', 'Candidatures'), ('matching', 'Scores de Matching')], max_length=20)),
                ('periode', models.CharField(choices=[('week', 'Cette semaine'), ('month', 'Ce mois'), ('year', 'Cette année')], max_length=20)),
                ('titre', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to='rapports/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('recruteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
