# Generated by Django 5.2 on 2025-10-17 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0007_rapport'),
    ]

    operations = [
        migrations.AddField(
            model_name='offreemploi',
            name='recruteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offres', to=settings.AUTH_USER_MODEL),
        ),
    ]
