# Generated by Django 5.2 on 2025-10-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0008_offreemploi_recruteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='score_matching',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
